name: 'Build and deploy Jekyll website'
description: 'Build and deploy Jekyll website to another branch'
author: 'danbraj'
inputs: 
  greet:
    description: 'Whos to greet?'
    default: 'Daniel'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.greet }}
branding:
  icon: 'wind'
  color: 'blue'